site_name: Solution Name


theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    - toc.follow
    - navigation.top
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  custom_dir: docs/overrides
  logo: assets/images/ibm.png

extra:
  generator: false


extra_css:
  - overrides/custom.css

repo_url: https://github.com/ibm-client-engineering/solution-template/

markdown_extensions:
  - toc:
      permalink: true
  - admonition


